- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/DynamoDBTable.scala
- app/com/gu/floodgate/ErrorResponse.scala
- app/com/gu/floodgate/contentsource/ContentSourceApi.scala
- app/com/gu/floodgate/jobhistory/JobHistoryService.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- app/com/gu/floodgate/runningjob/RunningJobService.scala
- conf/routes
- public/components/contentSource.react.js
- public/components/jobHistory.react.js
- public/components/reactApp.react.js
- public/components/reindex.react.js
- public/components/runningReindex.react.js
- public/services/contentSourceService.js
This PR adds the following:
- Ability to initiate a reindex for a content source via the UI.
- When a reindex is initiated, a progress indicator is displayed on the UI. This does not currently update itself with progress (this is to come).
- Ability to cancel a reindex. When cancelling a reindex, the progress indicator will disappear and the UI will update the job history with the newly cancelled item.
> Enable reindex via ui

- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/DynamoDBTable.scala
- app/com/gu/floodgate/jobhistory/JobHistory.scala
- app/com/gu/floodgate/jobhistory/JobHistoryTable.scala
- app/com/gu/floodgate/reindex/Progress.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- app/com/gu/floodgate/reindex/ProgressTrackerController.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- app/com/gu/floodgate/runningjob/RunningJob.scala
- app/com/gu/floodgate/runningjob/RunningJobService.scala
- app/com/gu/floodgate/runningjob/RunningJobTable.scala
- conf/application.conf
- conf/routes
- package.json
- public/components/reindex.react.js
- public/components/runningReindex.react.js
This change implements reindex progress updates against a fake endpoint inside that
application for now that fakes the response that we would expect to receive from a potential
client.
[Polling actor modelled on @cb372's really nice implementation in Pubflow]
> Provide progress updates for running reindexes.

- app/com/gu/floodgate/contentsource/ContentSource.scala
- app/com/gu/floodgate/contentsource/ContentSourceTable.scala
- public/components/contentSource.react.js
- public/components/contentSourceCreate.react.js
- public/components/contentSourceEdit.react.js
- public/components/reindexController.react.js
- public/components/reindexForm.react.js
- public/components/runningReindex.react.js
The reindex operations of different content sources vary in time, with some being extremely quick (tags & sections) to some taking much longer. Therefore it does not make sense for applications that reindex quickly to implement the ability to cancel a reindex or to allow a reindex for a specific time period necessarily. This pull request provides the flexibility for this and reflects it in the UI.
> Provide settings per content source to allow for differences between them.

- cloudformation.json
We have a wildcard cert for capi.gutools these days, so there's no reason not to use HTTPS.
Note that the callback URL for Google auth will need to be updated in the config file on S3 and in the Google developer dashboard.
> Switch to HTTPS

- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/Login.scala
- build.sbt
- conf/application.conf
- conf/routes
[Previous changes](https://github.com/guardian/floodgate/pull/48) were failing to deploy as 
play-googleauth didn't yet support Play 2.6. These changes reflect the latest version.
> Fix to Play 2.6 Upgrade

- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/DynamoDBTable.scala
- app/com/gu/floodgate/ErrorResponse.scala
- app/com/gu/floodgate/Formats.scala
- app/com/gu/floodgate/contentsource/ContentSourceApi.scala
- app/com/gu/floodgate/jobhistory/JobHistoryService.scala
- app/com/gu/floodgate/reindex/BulkJobActor.scala
- app/com/gu/floodgate/runningjob/RunningJobService.scala
- conf/application.conf
- conf/routes
- public/components/bulkReindexController.react.js
- public/components/bulkReindexes.react.js
- public/components/navigation.react.js
- public/components/reindexController.react.js
- public/components/runningReindex.react.js
- public/routes/routes.js
- public/services/contentSourceService.js
This change provides the ability to:
- Trigger bulk reindexes by `stack-stage`
- Have reindexes run in different environments in parallel
- Will not run if manual reindexes are in progress
- Will not allow reindexes to be ran in bulk mode
- Cancel individual running & pending reindexes
**To do:** 
Below is an example of the reindexes list:
> Add capability to handle batch reindexing jobs

- app/com/gu/floodgate/reindex/Progress.scala
The Status of a reindex job is serialised with a capital initial letter, but matched against an all-lowercase one during deserialisation. As a result, the last jobs are marked as "unknown" in the console:
Now:
> Make sure status is properly decoded

- cloudformation.yml
_Something_ in the build pipeline creates the .tgz file as `content-api-floodgate-0.1.0-SNAPSHOT.tgz` but the CFN scripts go looking for a `...-0.1-SNAPSHOT.tgz` 😞 
I haven't been able to test this because I don't have full XCode, and can't install it because I'm 0.0.1 versions behind the required MacOS version 🤦‍♂ 
Let's see if this helps - the app can't start up at the moment anyway.
> Temp fix, but _should_ get us running again (built as 0.1.0-SNAPSHOT)

- content-api-floodgate.service
~~Concierge~~ Floodgate is frequently failing ELB health checks. And the frequency increases when re-indexing operations are performed. 
I suspect its due to the JVM being out of memory - in my experience a max heap size of 200MB is too small to run a Play application. 
For now, bump it to what it was prior to #64. I've also ssh'd onto the instance and confirmed from the current memory usage this increase is within the instance's capacity.
This PR is of particular importance as we will be making extensive use of this app as part of our work to improve reindexing. If the health check continues to fail after this change, then we'll have to consider moving to a `t3.micro` (maybe verifying that lack of memory is the issue as a preliminary task).
> Increase max heap size

- cloudformation.yml
- riff-raff.yaml
Adds configuration to enable the Wazuh service. We should already be running on `ubuntu-bionic-capi` so the service should be available, just unable to communicate with the outside. We're also switching to the encrypted AMI version (assuming that we can for this project).
When this new configuration is deployed, you can see the status of the Wazuh agent using the following command:
```
ssm cmd -c "service wazuh-agent status | grep Active && journalctl -u wazuh-agent | grep -E \"(Valid|error)\"" -t floodgate,content-api,PROD -p capi
```
which should give us a `Valid` response.
Floodgate instance(s) will be visible to the security team. And Floodgate will continue to work, obvs!
We potentially can't reindex properly if Floodgate breaks.
N/A
N/A
> Set up for Wazuh and use encrypted AMI (because why not?)

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
Allow public access. WAF is manually configured in front of the ALB and openID applied on the ALB, in addition to the existing auth in the app
You can log in
You can log in
> Update access methodology

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
Adjusts outgoing instance SGs to not block access to the Flex re-index endpoints
Tested on CODE. Attempt a flexible content re-index, looking at the logs. Without this, you get a timeout error after 2mins. With it, the re-index proceeds
> Fix hanging reindexes

- .github/workflows/build.yaml
- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/Application.scala
- build.sbt
- cdk/instance-startup.sh
- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
- conf/routes
- riff-raff.yaml
- test/com/gu/floodgate/FloodgateIntegrationSpec.scala
- test/com/gu/floodgate/HealthcheckSpec.scala
- test/com/gu/floodgate/contentsource/ContentSourceReindexUrlTest.scala
- test/com/gu/floodgate/reindex/DateParametersTest.scala
Follow-on from #106 
- Tells `scalac` to target JVM-11 runtime environment
- Adds Prometheus for JVM metrics and sets up egest to AMP
- Tested Graviton (ARM) compatibility
Just deploy it and see if it runs. Check the logs under "Floodgate" in Central ELK / Content Platforms
It should be neat, tidy and monitorable :)
n/a
> Modernisation PR #2 - Java11 & JVM metrics

- public/components/navigation.react.js
Fixes a frontend bug which was introduced because `ramda` changed their export semantics 🤷 
Run locally with `npm run build-dev`.  The frontend should load up properly
No frontend crashes.
> fix imports from ramda

- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/contentsource/ContentSourceApi.scala
- app/com/gu/floodgate/contentsource/ContentSourceTable.scala
- app/com/gu/floodgate/reindex/BulkJobActor.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- app/com/gu/floodgate/reindex/ProgressTrackerController.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- build.sbt
- project/build.properties
Switches our internal use of Akka (actors, streams etc.) to use Apache Pekko instead.
Run it up and do some re-indexes.  It should still work....
No license/vuln issues when Akka 2.6 goes out of support
> Switch to using Pekko instead of Akka internally

- build.sbt
Snyk raised 1 high vuln in jetty-http package in floodgate.
Recommended versions to upgrade is to @9.4.53.v20231009, @10.0.16, @11.0.16
It is upgraded to 11.0.16 but tests were failing with exception 
so added `logback classic` library to fix. 
referred doc for which library to in case of NOP slf4j library is there - https://www.slf4j.org/codes.html#noProviders
`sbt test`
and run locally as given in readme file just to make sure floodgate is running.
and than run `snyk test --org=guardian-capi --all-projects` 
Tests should pass.
Floodgate should overcome by high vuln in snyk.
Note-Hope, addition of `logback-classic` should be able to do what is intended. 
Will wait for team's review as well.
> Fix snyk high vuln in jetty-http package.

- app/com/gu/floodgate/jobhistory/JobHistory.scala
- app/com/gu/floodgate/reindex/BulkJobActor.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- public/components/jobHistory.react.js
Reindex history captures the expected and indexed document counts from running jobs and persists them.
It's not obvious to the casual reindex users that this information is available.
It's visual in the Flexible Content reindex API but no in our UI.
Surface these counts as part of our reindex early / reindex often ethos.
Also surfaces that some content items are not Streamable and the indexed count does somethings fall short of expected count.
Document counts start to persist. This visibility gives us insight into which content sources are sending meaningful amounts of count.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with …
> Persist and surface reindexing document counts

- .gitignore
- build.sbt
- project/plugins.sbt
This change upgrades the version of Play and Logback to fix a security issue reported by Snyk:
https://app.snyk.io/org/guardian-capi/project/ad3b68a3-bbb7-4d10-86b1-88a89bc39409#issue-SNYK-JAVA-CHQOSLOGBACK-6094942
I have also removed some explicit dependencies on individual built-in Play components (for example `play-json`). It isn't neccessary to reference them explicitly in the dependencies because we are bringing in Play via the plugin, and this allows us to keep the versions consistent.
I have deployed this on PROD, and have done a small reindex, and checked that we are still logging.
> Upgrade Play and Logback for Snyk

- app/com/gu/floodgate/AppComponents.scala
- build.sbt
Update to latest google auth library and drop unused overrides.
Likely enforces 2FA.
We should be trying to drop as many overrides as we can as the frameworks we depend on catch up with better dependencies of their own.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Google auth 240

- .github/workflows/build.yaml
Saw a recent email from DevX about upgrading, figured I’d do it quickly. Version 4 means we can get rid of the AWS credentials step and leaves us less vulnerable to credentials access by malicious dependencies
See [the release notes for version 4](https://github.com/guardian/actions-riff-raff/releases/tag/v4) and [those for version 3](https://github.com/guardian/actions-riff-raff/releases/tag/v3.0.0) (the latter necessary because we’re coming from version 2.)
(Have also committed auto-formatting done by my editor, hope that’s ok)
> Update to actions-riff-raff@v4

- build.sbt
Update awsClientVersion to 1.12.671 to fix snyk high vulnerability
`./scripts/start.sh` to check that application front page displayed at https://localhost:9000
`sbt test` - tests pass
`snyk test` - no high vulnerabilities listed
Floodgate runs
Tests pass
No high vulnerabilities listed
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey …
> Update awsClientVersion re high snyk vulnerability

- app/com/gu/floodgate/contentsource/ContentSource.scala
- test/com/gu/floodgate/contentsource/ContentSourceSpec.scala
Preserves the ID property passed to `apply` when `ContentSource`s are created from `ContentWithoutEnvironmentOrId`s.
This looks like an oversight in [this commit](https://github.com/guardian/floodgate/commit/ca44162b76bc2a6283f2f19f4174284ada61743b), preserving [id generation in the original apply method](https://github.com/guardian/floodgate/blame/42a954abc00095c4cf904181245d09bdd130c764/app/com/gu/floodgate/contentsource/ContentSource.scala) and missing the shadowed variable. 
The result is a new content source every time you make an edit. If this PR is correct, it seems like it's either very rare that we use 'edit' in this way, or it ... has never happened 😅 
- The automated tests should pass. They're arguably overkill but it felt strange shipping an important fix without tests.
- …
> Do not duplicate content sources on edit

- .gitignore
- app/com/gu/floodgate/contentsource/ContentSource.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- public/components/contentSourceCreate.react.js
- public/components/contentSourceEdit.react.js
- public/components/headersForm.js
- test/com/gu/floodgate/contentsource/ContentSourceReindexUrlTest.scala
- test/com/gu/floodgate/contentsource/ContentSourceSpec.scala
Permit adding, removing and editing headers to floodgate content sources, and send those headers when making requests.
The latter part is currently untested, although simple to add ([3f13bd1](https://github.com/guardian/floodgate/pull/146/commits/3f13bd1386f7e56cf9d3f725848d137bf30f6184)) — if there's appetite perhaps we could use [play-mockws](https://github.com/leanovate/play-mockws) to add a test.
- Add a new content source. You should be able to add arbitrary headers. Or not.
- Inspect the content source after refreshing the page. The headers should be present in the UI.
- Edit the content source, adding and removing headers. This should also work as expected.
> Permit adding, removing and editing headers for floodgate content sources' reindex requests

- .github/workflows/build.yaml
Bumps the version of the action which posts test results, to avoid builds failing on "secondary rate limit"
If it builds, it's working 😁 
Working builds
n/a
> Fix annoying secondary rate limit issue in build

- .github/workflows/build.yaml
- .tool-versions
As we're so dependent on `sbt` and the `sbt launcher` hence we should provide this in our workflow so that external dependency wouldn't matter such as we had failed workflows on upgraded version of ubuntu recently because it has no sbt information in it.
So, to save us from these kind of issues we will provide our own setup-sbt as an action to resolve sbt easily.
Raise this PR and observe running CI.
Build should run as normal and no failing CI should be observed.
> Add setup-sbt to workflow

- riff-raff.yaml
Focal is no longer supported. Move to Jammy.
Deploy it to PROD. If that fails, revert and redeploy. It'll likely be a hard fail if it doesn't work, so we're not expecting to have to figure out subtleties.
If it deploys, we can run a couple of trial tasks with it, but TBH if it runs it's likely just fine.
Risks are minimal, we're expecting a pretty binary outcome, which we can revert if things do act up.
N/A
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.m …
> Upgrade OS via new AMI

- .github/workflows/build.yaml
Update the triggers for CI as building per push is a bit excessive and isn't necessary. Additionally, following https://github.com/guardian/floodgate/pull/166, configure `guardian/actions-riff-raff` to not comment on PRs as we should avoid deploying feature branches to PROD.
<details><summary>Additional benefits</summary>
<p>
The commenting behaviour of https://github.com/guardian/actions-riff-raff inspects the calling payload and tries to associate it with a pull request.
If the build triggered on push completes before the PR is opened[^1], a comment is not produced. Any subsequent commits to a PR will yield a comment. This is a little confusing.
This should fix that. By triggering the workflow on `pull_request` we know that `guardian/actions-riff-raff` will be able to locate a PR to …
> ci: Update triggers

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
- cdk/package.json
- cdk/yarn.lock
> [!NOTE]
> Easiest to review [commit by commit](https://github.com/guardian/floodgate/pull/170/commits).
Updates the version of [GuCDK](https://github.com/guardian/cdk) to 61.5.0. This is not the latest version, however 61.5.0 does require multiple deployments as described in the [release notes](https://github.com/guardian/cdk/releases/tag/v61.5.0). Therefore, I plan to raise a follow-up PR to this with part 2 of the 61.5.0 update, then continue with the version bumps.
Additionally as this is an update across 11 major versions, I've tried to add a commit for each of the more significant version updates. Therefore it is easiest to review [commit by commit](https://github.com/guardian/floodgate/pull/170/commits).
The update to the snapshot tests show the infrastructure changes - CI passing …
> chore(deps): Update GuCDK from 50.10.6 to 61.5.0

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
- cdk/package.json
- cdk/yarn.lock
Updates GuCDK to the current latest version. I've split the most relevant changes across commits, so it'll be easiest to review [commit by commit](https://github.com/guardian/floodgate/pull/172/commits).
> chore(deps): Update GuCDK to current latest (61.10.1)

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
- riff-raff.yaml
We've created private subnets in our `content-platforms-{STAGE}` stacks, so now we can move this service instance over to there and surrender our public IP addresses, which we don't need anyway 🎉 
We only have a PROD instance of floodgate, so we'd have to test there. However this does follow almost exactly the same pattern as https://github.com/guardian/apple-news/pull/466, which we know worked successfully.
Also, floodgate is only of internal interest, so if it doesn't quite go as expected for some reason, it's not going to break the world.
Deploy and kick off a test reindex. If it works, success!
Risks are minimal. We can redeploy the last good build very quickly, or we can revert and take stock if needs be.
N/A
-   [ ] [Tested with screen …
> Relocate instance into private subnets
