- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/AppLoader.scala
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/Login.scala
- conf/application.conf
- conf/routes
- project/Build.scala
- test/com/gu/floodgate/ApplicationSpec.scala
Have provided credentials for dev, code and prod.
> Secure application with play google auth.

- .gitignore
- app/com/gu/floodgate/Application.scala
- app/com/gu/floodgate/views/app.scala.html
- app/com/gu/floodgate/views/layout.scala.html
- conf/routes
- package.json
- public/app.js
- public/build_config/webpack.dev.conf.js
- public/build_config/webpack.prod.conf.js
- public/components/reactApp.react.js
- scripts/setup.sh
- scripts/start.sh
- This should provide a working example for the rendering of a basic react component.
> Introduce client side dependencies to application.

- conf/application.conf
Use gzip compression to save :pound:
> Use gzip compression for web services

- app/com/gu/floodgate/DynamoDBTable.scala
- app/com/gu/floodgate/contentsource/ContentSource.scala
- app/com/gu/floodgate/contentsource/ContentSourceApi.scala
- app/com/gu/floodgate/contentsource/ContentSourceService.scala
- app/com/gu/floodgate/contentsource/ContentSourceTable.scala
- app/com/gu/floodgate/jobhistory/JobHistory.scala
- app/com/gu/floodgate/jobhistory/JobHistoryService.scala
- app/com/gu/floodgate/jobhistory/JobHistoryTable.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- app/com/gu/floodgate/reindex/ProgressTrackerController.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- app/com/gu/floodgate/runningjob/RunningJob.scala
- app/com/gu/floodgate/runningjob/RunningJobApi.scala
- app/com/gu/floodgate/runningjob/RunningJobService.scala
- app/com/gu/floodgate/runningjob/RunningJobTable.scala
- conf/routes
- public/components/contentSource.react.js
- public/components/contentSourceCreate.react.js
- public/components/contentSourceEdit.react.js
- public/components/navigation.react.js
- public/components/reindexController.react.js
- public/components/reindexForm.react.js
- public/components/runningReindex.react.js
- public/routes/routes.js
- public/services/contentSourceService.js
Change the way we store and retrieve content source by making it contextual to its environment (LIVE|DRAFT|CODE|PROD)
> Change the way we store and retrieve content source

- public/components/navigation.react.js
- public/components/reindexController.react.js
- public/services/contentSourceService.js
Make dropdown navigation more user friendly given the number of different content sources.
> Add navigation between environments

- app/com/gu/floodgate/jobhistory/JobHistory.scala
- app/com/gu/floodgate/jobhistory/JobHistoryTable.scala
- app/com/gu/floodgate/reindex/DateParameters.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
- app/com/gu/floodgate/runningjob/RunningJob.scala
- app/com/gu/floodgate/runningjob/RunningJobTable.scala
- public/components/jobHistory.react.js
- public/components/jobHistoryDateRange.react.js
- public/components/reindexController.react.js
- test/com/gu/floodgate/ApplicationSpec.scala
* Add the date range info to the JobHistory and RunningJob models and Dynamo tables
* Display that info in the job history table
> Show date range in history

- cloudformation.yml
* replaces missed account id
* makes listener list
🙈 🙈 🙈
> corrects cf template

- app/com/gu/floodgate/reindex/BulkJobActor.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- public/components/bulkReindexController.react.js
Accidentally deleted my branch & PR 😱 🙀  Read more here: https://github.com/guardian/floodgate/pull/53
> Fix hanging reindexes

- app/com/gu/floodgate/reindex/BulkJobActor.scala
- public/components/bulkReindexController.react.js
- public/components/bulkReindexes.react.js
- public/components/reindexController.react.js
> Fix for broken cancel button & progress bar render

- content-api-floodgate.service
instances were dying every day
> Increase app memory

- cloudformation.yml
To support ssh access using ssm
> Attach AmazonEC2RoleforSSM

- cloudformation.yml
Pretty simple change.
Before:
After:
> Upgrade t2.nano -> t3.nano

- cloudformation.yml
- content-api-floodgate.service
Follow up from #75.
With the changes in #75 ELB system health check still failing. If this PR doesn't stop these, then we will have to consider more in-depth analysis.
> Update instance size and memory usage

- app/com/gu/floodgate/reindex/ProgressTracker.scala
- build.sbt
Additional logging around content source progress update failures.
Level the AWS client while this deployable has our attention.
> Update fail log

- app/com/gu/floodgate/AppComponents.scala
- app/com/gu/floodgate/contentsource/ContentSourceApi.scala
- app/com/gu/floodgate/reindex/ProgressTracker.scala
- app/com/gu/floodgate/reindex/ReindexService.scala
Log out if a content source fails our not unreasonable request for a reindex.
> Logging around initial reindex request fails.

- riff-raff.yaml
Move floodgate to a ubuntu 18 LTS base image which has Java 8.
Tested by deploying from branch. Works OK.
> Use bionic base image

- public/build_config/webpack.dev.conf.js
- public/build_config/webpack.prod.conf.js
See #88 for the first take on this PR. This is the same PR, with an added fix for resolving the correct path for `app.js` in the webpack config.
It has been tested, deployed to PROD, and completed successful reindexes.
> Bump node to 14.6.1 (and clean up dependency rot) #2

- build.sbt
- package.json
- project/build.properties
- project/plugins.sbt
- yarn.lock
update to play 2.8, latest 1.x AWS SDK etc. for dependencies
Also updates `node-sass` for frontend dependencies
Run it up in CODE and check
Less security alerts
There are some fairly hefty dependency changes so we should check that everything is working as planned
> Snyk dependency updates

- build.sbt
Brings down 1 Critical and 1 Medium vulnerabilities
> Override dependency with critical vuln

- cdk/lib/__snapshots__/floodgate.test.ts.snap
- cdk/lib/floodgate.ts
- cdk/package.json
- cdk/yarn.lock
Bumps the CDK library versions to avoid identified vulns
If it builds, it works :)
Less alerts
> bump CDK dependencies

- build.sbt
Logback library upgraded in its patch version to fix high vulns reported by snyk.
sbt test
snyk test
high vulns should be solved.
tests are passing.
floodgate should be running as expected. (tested and its running fine)
> fix high vulns in logback
